### ISSUE TITLE
Xamarin binding not working with NR

### ISSUE THREAD

**Issue by Kanwar14** [newrelic-experimental/newrelic-xamarin-binding#5]
We have followed the step in this project , but are unable to fetch any mobile metrics in New Relic.

**Comment by vvydier** [comment]
Are you able to build the bindings for iOS and Android? What errors are you getting on msbuild?

**Comment by Kanwar14** [comment]
++ Adding Ankit.

***@***.***

Hi Ankit,

Were we getting any errors? 

Thanks and regards,
Kanwardeep Singh

**Comment by Kanwar14** [comment]
++

**Comment by Kanwar14** [comment]
We were able to build the bindings without an error.

**Comment by vvydier** [comment]
Thanks @Kanwar14  for letting me know, I will go ahead and close the issue

**Comment by Kanwar14** [comment]
It meant that there hasnt been any error , but there isnt any data on New relic.
